#!/usr/bin/env bash

set -xe

LIB="/usr/lib/mpi"
NGINX="etc/nginx/sites-available"
SYSTEMD="etc/systemd/system"

ssh root@ckserv.net "true \
    && mkdir -p /var/lib/mpi \
    && cp $LIB/dist/$SYSTEMD/mpi-gunicorn.service /$SYSTEMD/ckserv-mpi-gunicorn.service \
    && cp $LIB/dist/$SYSTEMD/mpi-process.service /$SYSTEMD/ckserv-mpi-process.service \
    && cp $LIB/dist/$SYSTEMD/mpi-process.timer /$SYSTEMD/ckserv-mpi-process.timer \
    && systemctl daemon-reload \
    && systemctl enable ckserv-mpi-gunicorn.service \
    && systemctl restart ckserv-mpi-gunicorn.service \
    && systemctl enable ckserv-mpi-process.service \
    && systemctl enable ckserv-mpi-process.timer \
    && systemctl start ckserv-mpi-process.timer"
