#!/usr/bin/env bash

set -xe

CURRENT="$(dirname "$0")"
ROOT_DIR="$CURRENT/.."
DIST_DIR="$ROOT_DIR/dist"
TARGET="root@ckserv.net"

# App
rsync -r -a --progress --exclude mpi/config.py "$ROOT_DIR" "$TARGET:/usr/lib/mpi"
